### ISSUE TITLE
Naming Job ?

### ISSUE THREAD

**Issue by revskill10** [cdrx/faktory_cron#1]
I have a job called TestWorker (i'm using Ruby), then run with faktory-worker to load that worker.
Then i put TestWorker as job name in crontab.yaml.
But the system doesn't recognize that name to run.
Am i missing something ?

**Comment by cdrx** [comment]
Can you paste the `crontab.yaml` file, and the output from running `faktory-cron` please?

**Comment by revskill10** [comment]
The log from worker is
```
2018-01-09T11:51:10.469Z 34247 TID-ouioeasno WARN: NameError: uninitialized constant TestWorker
```
My ruby class is
```
require 'connection_pool'
require 'faktory'
require 'securerandom'


class TestWorker
  include Faktory::Job

  def perform(*args)
    #
    sleep 1
  end
end

```

**Comment by revskill10** [comment]
Ah, my mistake, i didn't require it when starting with faktory-worker. 
Thanks.
